all:
	pip install -r requirements.txt

compile:
	python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. .\proto_files\smartclass.proto

s:
	python server.py

c:
	python client.py

env:
	.\env\Scripts\Activate.ps1