# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_files import smartclass_pb2 as proto__files_dot_smartclass__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto_files/smartclass_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartClassStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.joinRoom = channel.unary_stream(
                '/smartclass.SmartClass/joinRoom',
                request_serializer=proto__files_dot_smartclass__pb2.JoinRoomRequest.SerializeToString,
                response_deserializer=proto__files_dot_smartclass__pb2.JoinRoomResponse.FromString,
                _registered_method=True)
        self.getNextQuestion = channel.unary_unary(
                '/smartclass.SmartClass/getNextQuestion',
                request_serializer=proto__files_dot_smartclass__pb2.NextQuestionRequest.SerializeToString,
                response_deserializer=proto__files_dot_smartclass__pb2.Question.FromString,
                _registered_method=True)
        self.submitAnswer = channel.unary_unary(
                '/smartclass.SmartClass/submitAnswer',
                request_serializer=proto__files_dot_smartclass__pb2.Answer.SerializeToString,
                response_deserializer=proto__files_dot_smartclass__pb2.GameStatus.FromString,
                _registered_method=True)


class SmartClassServicer(object):
    """Missing associated documentation comment in .proto file."""

    def joinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNextQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartClassServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'joinRoom': grpc.unary_stream_rpc_method_handler(
                    servicer.joinRoom,
                    request_deserializer=proto__files_dot_smartclass__pb2.JoinRoomRequest.FromString,
                    response_serializer=proto__files_dot_smartclass__pb2.JoinRoomResponse.SerializeToString,
            ),
            'getNextQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.getNextQuestion,
                    request_deserializer=proto__files_dot_smartclass__pb2.NextQuestionRequest.FromString,
                    response_serializer=proto__files_dot_smartclass__pb2.Question.SerializeToString,
            ),
            'submitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.submitAnswer,
                    request_deserializer=proto__files_dot_smartclass__pb2.Answer.FromString,
                    response_serializer=proto__files_dot_smartclass__pb2.GameStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartclass.SmartClass', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartclass.SmartClass', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartClass(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def joinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/smartclass.SmartClass/joinRoom',
            proto__files_dot_smartclass__pb2.JoinRoomRequest.SerializeToString,
            proto__files_dot_smartclass__pb2.JoinRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getNextQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartclass.SmartClass/getNextQuestion',
            proto__files_dot_smartclass__pb2.NextQuestionRequest.SerializeToString,
            proto__files_dot_smartclass__pb2.Question.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartclass.SmartClass/submitAnswer',
            proto__files_dot_smartclass__pb2.Answer.SerializeToString,
            proto__files_dot_smartclass__pb2.GameStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
